### ISSUE TITLE
Not working follow the guide when use with express.

### ISSUE THREAD

**Issue by mrdulin** [senecajs/seneca-web#135]
Here is the error log when `npm start`

```bash
~/workspace/nodejs-microservice(master ✗) npm start

> nodejs-microservice@1.0.0 start /Users/elsa/workspace/nodejs-microservice
> node index.js

{"notice":"seneca: Action init:web failed: route.pin.replace is not a function.","code":"act_execute","err":{"eraro":true,"orig":{},"code":"act_execute","seneca":true,"package":"seneca","msg":"seneca: Action init:web failed: route.pin.replace is not a function.","details":{"message":"route.pin.replace is not a function","pattern":"init:web","instance":"Seneca/4gr3erdrrf8q/1521469167159/4971/3.4.3/-","orig$":{},"message$":"route.pin.replace is not a function","plugin":{}},"callpoint":"at _.mapKeys (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:50:33)"},"actid":"uchzxx5673t2/y850ib62kvw9","msg":{"init":"web","default$":{},"fatal$":true,"local$":true,"plugin$":{"name":"web","tag":"-","fullname":"web"},"tx$":"y850ib62kvw9"},"meta":{"start":1521469167366,"end":1521469167367,"pattern":"init:web","action":"init_22","mi":"n5e8ea1sukty","tx":"y850ib62kvw9","id":"n5e8ea1sukty/y850ib62kvw9","instance":"4gr3erdrrf8q/1521469167159/4971/3.4.3/-","tag":"-","seneca":"3.4.3","version":"0.1.0","gate":false,"fatal":true,"local":true,"timeout":22222,"dflt":{},"plugin":{"name":"web","tag":"-","fullname":"web"},"parents":[["name:web,plugin:define,role:seneca,seq:2,tag:undefined","uchzxx5673t2/y850ib62kvw9","4gr3erdrrf8q/1521469167159/4971/3.4.3/-","-","0.1.0",1521469167345,null,false,"plugin_definition_8"]],"sync":true,"trace":[],"sub":null,"data":null,"err":null,"err_trace":null,"error":true,"empty":null},"actdef":{"plugin_name":"web","plugin_tag":"-","plugin_fullname":"web","raw":{"init":"web"},"plugin":{"name":"web","tag":"-","fullname":"web"},"sub":false,"client":false,"rules":{},"id":"init_22","name":"init","pattern":"init:web","msgcanon":{"init":"web"},"priorpath":""},"client":false,"listen":false,"transport":{},"kind":"act","case":"ERR","duration":1,"level":"error","plugin_name":"web","pattern":"init:web","seneca":"4gr3erdrrf8q/1521469167159/4971/3.4.3/-","when":1521469167372}
[]


Seneca Fatal Error
==================

Message: seneca: Action init:web failed: route.pin.replace is not a function.

Code: act_execute

Details: { message: 'route.pin.replace is not a function',
  pattern: 'init:web',
  fn: [Function: init],
  cb: [Function],
  instance: 'Seneca/4gr3erdrrf8q/1521469167159/4971/3.4.3/-',
  callpoint: undefined,
  'orig$':
   TypeError: route.pin.replace is not a function
       at _.mapKeys (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:50:33)
       at /Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:13341:33
       at /Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:4944:15
       at baseForOwn (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:3001:24)
       at Function.mapKeys (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:13340:7)
       at _.each (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:14:7)
       at arrayEach (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:537:11)
       at Function.forEach (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:9359:14)
       at mapper (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:13:5)
       at Seneca.mapRoutes (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/web.js:63:16),
  'message$': 'route.pin.replace is not a function',
  plugin: {} }

Stack:
    at _.mapKeys (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:50:33)
    at /Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:13341:33
    at /Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:3001:24)
    at Function.mapKeys (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:13340:7)
    at _.each (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:14:7)
    at arrayEach (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/elsa/workspace/nodejs-microservice/node_modules/lodash/lodash.js:9359:14)
    at mapper (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/lib/mapper.js:13:5)
    at Seneca.mapRoutes (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca-web/web.js:63:16)

Instance: Seneca/4gr3erdrrf8q/1521469167159/4971/3.4.3/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance)
    at Object.intern.handle_reply (/Users/elsa/workspace/nodejs-microservice/node_modules/seneca/seneca.js:1318:23)

When: 2018-03-19T14:19:27.384Z

Log: {kind:null,plugin:seneca,tag:3.4.3,id:4gr3erdrrf8q/1521469167159/4971/3.4.3/-,code:act_execute,notice:seneca: A

Node:
  { http_parser: '2.7.0', node: '8.4.0', v8: '6.0.286.52', uv: '1.13.1', zlib: '1.2.11', ares: '1.10.1-DEV', modules: '57', nghttp2: '1.22.0', openssl: '1.0.2l', icu: '59.1', unicode: '9.0', cldr: '31.0.1', tz: '2017b' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_alpn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'Binding config', 'NativeModule events', 'Binding async_wrap', 'Binding icu', 'NativeModule util', 'NativeModule internal/errors', 'NativeModule internal/encoding', 'NativeModule internal/util', 'Binding util', 'Binding constants', 'Binding buffer', 'Binding uv', 'NativeModule buffer', 'NativeModule internal/buffer', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule internal/linkedlist', 'NativeModule async_hooks', 'NativeModule assert', 'Binding inspector', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'NativeModule path', 'Binding fs', 'NativeModule stream', 'NativeModule internal/streams/legacy', 'NativeModule _stream_readable', 'NativeModule internal/streams/BufferList', 'NativeModule internal/streams/destroy', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'Binding fs_event_wrap', 'NativeModule internal/fs', 'NativeModule internal/url', 'NativeModule internal/querystring', 'NativeModule querystring', 'Binding url', 'NativeModule internal/process', 'NativeModule internal/process/warning', 'NativeModule internal/process/next_tick', 'NativeModule internal/process/promises', 'NativeModule internal/process/stdio', 'NativeModule http', 'NativeModule _http_agent', 'NativeModule net', 'NativeModule internal/net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding pipe_wrap', 'Binding stream_wrap', 'NativeModule _http_client', 'NativeModule url', 'Binding http_parser', 'NativeModule _http_common', 'NativeModule internal/freelist', 'NativeModule internal/http', 'NativeModule _http_incoming', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule https', 'NativeModule tls', 'Binding crypto', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule string_decoder', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule os', 'Binding os', 'NativeModule tty', 'Binding signal_wrap', 'NativeModule zlib', 'Binding zlib', 'NativeModule console' ]

Process:
  pid=4971, arch=x64, platform=darwin,
  path=/usr/local/bin/node,
  argv=[ '/usr/local/bin/node',  '/Users/elsa/workspace/nodejs-microservice/index.js' ],
  env={ npm_config_save_dev: '',  npm_config_legacy_bundling: '',  npm_config_dry_run: '',  AUTOJUMP_ERROR_PATH: '/Users/elsa/Library/autojump/errors.log',  npm_config_viewer: 'man',  npm_config_only: '',  npm_config_browser: '',  npm_package_gitHead: 'a6af88ba41a6652ee15e27049556b1c083273576',  npm_config_also: '',  npm_config_rollback: 'true',  TERM_PROGRAM: 'iTerm.app',  NODE: '/usr/local/bin/node',  npm_config_usage: '',  npm_package_homepage: 'https://github.com/mrdulin/nodejs-microservice#readme',  AUTOJUMP_SOURCED: '1',  npm_config_globalignorefile: '/usr/local/etc/npmignore',  TERM: 'xterm-256color',  SHELL: '/bin/zsh',  npm_config_shell: '/bin/zsh',  npm_config_maxsockets: '50',  npm_config_init_author_url: '',  npm_config_shrinkwrap: 'true',  npm_config_parseable: '',  npm_config_metrics_registry: 'https://registry.npm.taobao.org/',  TMPDIR: '/var/folders/05/8s4ztth56tj1s2mryq4j37d00000gn/T/',  npm_config_timing: '',  npm_config_init_license: 'ISC',  Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.23O9jn7P78/Render',  npm_config_if_present: '',  TERM_PROGRAM_VERSION: '3.1.5',  npm_config_sign_git_tag: '',  npm_config_init_author_email: '',  npm_config_cache_max: 'Infinity',  npm_config_long: '',  npm_config_local_address: '',  npm_config_git_tag_version: 'true',  npm_config_cert: '',  TERM_SESSION_ID: 'w0t0p0:25437839-0DC7-42AB-9645-DEAE5AF72EC5',  npm_config_fetch_retries: '2',  npm_config_registry: 'https://registry.npm.taobao.org/',  npm_package_repository_url: 'git+https://github.com/mrdulin/nodejs-microservice.git',  ZSH: '/Users/elsa/.oh-my-zsh',  npm_config_versions: '',  npm_config_message: '%s',  npm_config_key: '',  npm_package_readmeFilename: 'README.md',  npm_config_python: '/usr/bin/python',  npm_package_description: '',  USER: 'elsa',  npm_package_license: 'ISC',  npm_config_globalconfig: '/usr/local/etc/npmrc',  npm_package_dependencies_seneca_web_adapter_express: '^1.1.1',  npm_config_prefer_online: '',  npm_config_logs_max: '10',  npm_config_always_auth: '',  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.U9theZvtZI/Listeners',  npm_package_devDependencies_eslint: '^4.19.0',  __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',  npm_execpath: '/usr/local/lib/node_modules/npm/bin/npm-cli.js',  npm_config_global_style: '',  npm_config_cache_lock_retries: '10',  npm_config_cafile: '',  PAGER: 'less',  npm_config_heading: 'npm',  LSCOLORS: 'Gxfxcxdxbxegedabagacad',  npm_config_searchlimit: '20',  npm_config_proprietary_attribs: 'true',  npm_config_offline: '',  npm_config_fetch_retry_mintimeout: '10000',  npm_config_json: '',  npm_config_access: '',  npm_config_argv: '{"remain":[],"cooked":["start"],"original":["start"]}',  PATH: '/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/elsa/workspace/nodejs-microservice/node_modules/.bin:/usr/local/Cellar/rabbitmq/3.7.4/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/Cellar/mongodb/3.4.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS',  npm_config_allow_same_version: '',  npm_package_dependencies_seneca: '^3.4.3',  npm_config_https_proxy: '',  npm_config_engine_strict: '',  npm_config_description: 'true',  _: '/usr/local/bin/node',  npm_config_userconfig: '/Users/elsa/.npmrc',  npm_config_init_module: '/Users/elsa/.npm-init.js',  npm_package_author: '',  PWD: '/Users/elsa/workspace/nodejs-microservice',  npm_config_user: '',  npm_config_node_version: '8.4.0',  npm_package_bugs_url: 'https://github.com/mrdulin/nodejs-microservice/issues',  npm_lifecycle_event: 'start',  npm_config_save: 'true',  npm_config_ignore_prepublish: '',  npm_config_editor: 'vi',  npm_config_auth_type: 'legacy',  npm_package_repository_type: 'git',  npm_package_name: 'nodejs-microservice',  LANG: 'zh_CN.UTF-8',  npm_config_tag: 'latest',  npm_config_script_shell: '',  npm_package_devDependencies_eslint_plugin_import: '^2.9.0',  npm_package_dependencies_seneca_web: '^2.2.0',  npm_package_dependencies_body_parser: '^1.18.2',  ITERM_PROFILE: 'main',  npm_config_progress: 'true',  npm_config_global: '',  npm_package_scripts_start: 'node index.js',  npm_config_searchstaleness: '900',  npm_config_optional: 'true',  npm_config_ham_it_up: '',  XPC_FLAGS: '0x0',  npm_config_save_prod: '',  npm_config_force: '',  npm_config_bin_links: 'true',  npm_config_searchopts: '',  npm_config_depth: 'Infinity',  npm_package_main: 'index.js',  npm_config_sso_poll_frequency: '500',  npm_config_rebuild_bundle: 'true',  npm_package_devDependencies_eslint_config_airbnb_base: '^12.1.0',  npm_package_version: '1.0.0',  XPC_SERVICE_NAME: '0',  npm_config_unicode: 'true',  SHLVL: '2',  HOME: '/Users/elsa',  COLORFGBG: '15;0',  npm_config_fetch_retry_maxtimeout: '60000',  npm_package_scripts_test: 'echo "Error: no test specified" && exit 1',  npm_config_tag_version_prefix: 'v',  npm_config_strict_ssl: 'true',  npm_config_sso_type: 'oauth',  npm_config_scripts_prepend_node_path: 'warn-only',  npm_config_save_prefix: '^',  npm_config_loglevel: 'notice',  npm_config_ca: '',  npm_config_save_exact: '',  npm_config_group: '20',  npm_config_fetch_retry_factor: '10',  npm_config_dev: '',  npm_config_version: '',  npm_config_prefer_offline: '',  npm_config_cache_lock_stale: '60000',  npm_config_cache_min: '10',  ITERM_SESSION_ID: 'w0t0p0:25437839-0DC7-42AB-9645-DEAE5AF72EC5',  npm_config_searchexclude: '',  npm_config_cache: '/Users/elsa/.npm',  LESS: '-R',  LOGNAME: 'elsa',  npm_lifecycle_script: 'node index.js',  npm_config_color: 'true',  npm_config_proxy: '',  npm_config_package_lock: 'true',  npm_package_dependencies_seneca_mongo_store: '^1.1.0',  LC_CTYPE: 'zh_CN.UTF-8',  npm_config_save_optional: '',  npm_config_ignore_scripts: '',  npm_config_user_agent: 'npm/5.3.0 node/v8.4.0 darwin x64',  npm_config_cache_lock_wait: '10000',  npm_config_production: '',  npm_config_send_metrics: '',  npm_config_save_bundle: '',  npm_package_dependencies_express: '^4.16.3',  npm_config_umask: '0022',  npm_config_init_version: '1.0.0',  npm_config_init_author_name: '',  npm_config_git: 'git',  npm_config_scope: '',  npm_config_unsafe_perm: 'true',  npm_config_tmp: '/var/folders/05/8s4ztth56tj1s2mryq4j37d00000gn/T',  npm_config_onload_script: '',  npm_node_execpath: '/usr/local/bin/node',  npm_config_link: '',  npm_config_prefix: '/usr/local',  COLORTERM: 'truecolor' }




SENECA TERMINATED (on timeout) at 2018-03-19T14:19:38.499Z.


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nodejs-microservice@1.0.0 start: `node index.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the nodejs-microservice@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elsa/.npm/_logs/2018-03-19T14_19_38_509Z-debug.log
```

here is my repo: 

https://github.com/mrdulin/nodejs-microservice

Don't know why.

**Comment by tswaters** [comment]
Sorry for not responding sooner.

Based on the error, looks like `seneca-web` isn't receiving the routes properly.  The `pin` needs to be defined and a string.  If it's not a string, it'll probably blow up, especially if there's no replace function on `pin`.

Looks like there's a bunch of commits on that repo since you posted this issue.  Are you still having problems?

**Comment by mrdulin** [comment]
@tswaters the problem is solved. thanks for reply.
