### ISSUE TITLE
EventEmitter memory leak detected seems to stem from seneca

### ISSUE THREAD

**Issue by devotox** [senecajs/seneca-web#58]
```
api_1             | [ Nodemon ][ Error ] (node) warning: possible EventEmitter memory leak detected. 11 clear listeners added. Use emitter.setMaxListeners() to increase limit.
api_1             |
api_1             | [ Nodemon ][ Error ] Trace
api_1             |     at GateExecutor.addListener (events.js:252:17)
api_1             |     at GateExecutor.once (events.js:278:8)
api_1             |     at Seneca.api_ready [as ready] (/var/app/current/api/node_modules/seneca/seneca.js:923:30)
api_1             |     at meta.export (/var/app/current/api/node_modules/seneca-web/web.js:661:14)
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |     at Function.process_params (/var/app/current/api/node_modules/express/lib/router/index.js:330:12)
api_1             |     at next (/var/app/current/api/node_modules/express/lib/router/index.js:271:10)
api_1             |     at exports.log_api_request (/var/app/current/api/common/utils/api_response_handler.js:510:27)
api_1             |     at Layer.handle [as handle_request] (/var/app/current/api/node_modules/express/lib/router/layer.js:95:5)
api_1             |     at trim_prefix (/var/app/current/api/node_modules/express/lib/router/index.js:312:13)
api_1             |     at /var/app/current/api/node_modules/express/lib/router/index.js:280:7
api_1             |     at Function.process_params (/var/app/current/api/node_modules/express/lib/router/index.js:330:12)
api_1             |     at next (/var/app/current/api/node_modules/express/lib/router/index.js:271:10)
api_1             |     at SessionStrategy.strategy.pass (/var/app/current/api/node_modules/passport/lib/middleware/authenticate.js:325:9)
api_1             |

```

**Comment by geek** [comment]
@devotox thanks, what version of seneca are you running?

**Comment by devotox** [comment]
1.3.0

**Comment by mcdonnelldean** [comment]
Closed as releated to seneca directly and is noted there.
