### ISSUE TITLE
errors thrown in seneca action result in circular json error

### ISSUE THREAD

**Issue by tswaters** [senecajs/seneca-web#91]
This happens under express at least - I don't really use HAPI and haven't tried it there.

Consider the following:

```js
var server = Express()

var seneca = Seneca({log: 'test'}).use(Web, {adapter: 'express', context: server})

seneca.act('role:web', {routes: {pin: 'role:test,cmd:*',map: {error: true}}}, (err, res) => {

seneca.add('role:test,cmd:error', (msg, reply) => reply(new Error('aw snap!')))

server.listen('5002', (err) => {

Request('http://127.0.0.1:5002/error', (err, res, body) => {
  // explosions!!!
})  }) })
```

This will blow up in a fantastic manner due to a circular json reference.  Here is the stack trace:

```

Message: Converting circular structure to JSON

Code: undefined

Details: undefined

Stack:
    at Object.stringify (native)
    at Object.logger (C:\Code\seneca-web\node_modules\seneca\lib\logging.js:74:24)
    at Seneca.log (C:\Code\seneca-web\node_modules\seneca\seneca.js:1639:16)
    at Seneca.log_modifier (C:\Code\seneca-web\node_modules\seneca\seneca.js:1677:11)
    at Seneca.prepare_log_data [as log] (C:\Code\seneca-web\node_modules\seneca\seneca.js:1670:11)
    at Seneca.log_modifier (C:\Code\seneca-web\node_modules\seneca\seneca.js:1677:11)
    at Seneca.prepare_log_data [as log] (C:\Code\seneca-web\node_modules\seneca\seneca.js:1670:11)
    at Seneca.log_modifier (C:\Code\seneca-web\node_modules\seneca\seneca.js:1677:11)
    at Function.prepare_log_data [as error] (C:\Code\seneca-web\node_modules\seneca\seneca.js:1670:11)
    at act_error (C:\Code\seneca-web\node_modules\seneca\seneca.js:1224:18)
    at Seneca.act_done (C:\Code\seneca-web\node_modules\seneca\seneca.js:1009:21)
    at Seneca.<anonymous> (C:\Code\seneca-web\node_modules\seneca\seneca.js:1085:22)
    at Seneca.seneca.act.seneca.add (C:\Code\seneca-web\test\express.test.js:119:9)
    at Array.done (C:\Code\seneca-web\node_modules\seneca\seneca.js:950:22)
    at validate_action_message (C:\Code\seneca-web\node_modules\seneca\seneca.js:1398:19)
    at execute_action (C:\Code\seneca-web\node_modules\seneca\seneca.js:880:7)
    at Object.execspec.fn [as orig_fn] (C:\Code\seneca-web\node_modules\seneca\seneca.js:1084:11)
    at Object.timeout_fn [as fn] (C:\Code\seneca-web\node_modules\gate-executor\gate-executor.js:194:12)
    at next (C:\Code\seneca-web\node_modules\gate-executor\gate-executor.js:126:14)
    at process (C:\Code\seneca-web\node_modules\gate-executor\gate-executor.js:175:12)
    at Immediate.<anonymous> (C:\Code\seneca-web\node_modules\gate-executor\gate-executor.js:324:9)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Basically when the seneca action replies in the error, it goes into the logging and attempts to serialize both request$ and response$ - both of these are circular references and this blows everything up.

This is *probably* a [bug in the default logger](https://github.com/senecajs/seneca/blob/v3.1.0/lib/logging.js#L45) but I encountered it using seneca-web.

**Comment by tswaters** [comment]
I've submitted a pull request against seneca that fixes this:

https://github.com/senecajs/seneca/pull/556

It's not the cleanest solution, but it at least doesn't explode in a fire.

I would think that the logger shouldn't attempt to serialize `request$` and `response$` but I'm unsure if seneca-web has a way to tell it not to.

**Comment by tswaters** [comment]
That pull request was merged, so it won't blow up anymore - but, even then when a action goes into error the entire request$ and response$ objects are stringified and output to the logs which may not be ideal.

**Comment by mcdonnelldean** [comment]
Closed as PR merged. Good work @tswaters
